[teleports]
warpRequirements = [
    "[is_not_interdimensional] scaled_add_xp_cost(distance, 0.015)",
    "[is_interdimensional] add_xp_cost(40)",
    "[source_is_warp_plate] multiply_xp_cost(0)",
    "[source_is_warp_stone] add_durability_cost(80)",
    "[target_is_global] multiply_xp_cost(0)",
    "min_xp_cost(0)",
    "max_xp_cost(40)",
    "[source_is_inventory_button] add_cooldown(inventory_button, 300)"
]
