name: Build Client MRpack

on: push

permissions:
  contents: read

jobs:
  build-client-pack:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch pakmc binary
        uses: dsaltares/fetch-gh-release-asset@1.1.2
        with:
          repo: 0x1bd/pakmc
          file: pakmc

      - name: Grant executable permissions
        run: chmod +x pakmc
        
      - name: Build MRpack
        run: ./pakmc build client

      - name: Upload MRpack artifact
        uses: actions/upload-artifact@v4
        with:
          name: client-mrpack
          path: '**/*.mrpack'
          if-no-files-found: error
